[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:worker-1]
command=taskiq worker manifold.tasks.broker:broker --queues manual,sync
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker-2]
command=taskiq worker manifold.tasks.broker:broker --queues manual,sync
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker-3]
command=taskiq worker manifold.tasks.broker:broker --queues manual,sync
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=taskiq scheduler manifold.tasks.scheduler:scheduler
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
